# Generated by Django 6.0.1 on 2026-01-12 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalWalletApp', '0003_remove_wallet_child_remove_parent_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='DigitalWalletApp.parent'),
        ),
    ]
