# Generated by Django 6.0.1 on 2026-01-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalWalletApp', '0004_alter_student_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='spending_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='student',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
