# Generated by Django 6.0.1 on 2026-01-12 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalWalletApp', '0007_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(default='Purchase', max_length=255)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DigitalWalletApp.student')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DigitalWalletApp.vendor')),
            ],
        ),
    ]
